export const CREATE_TEMPLATES = {
  task_assignment: {
    id: 'task_assignment',
    actionTypes: ['add_task'],
    title: 'Task Assignment',
    eyebrow: 'Task',
    entity: 'Task',
    successLabel: 'Task assignment',
    submitLabel: 'Create Assignment',
    defaults: {
      shift_id: 'quick-add',
      status: 'pending',
      priority: 'medium',
      created_from_template: true,
      requires_photo: false,
      requires_approval: false,
    },
    fields: [
      { name: 'title', label: 'Task', type: 'text', required: true, placeholder: 'What needs to get done?' },
      {
        name: 'recipe_id',
        label: 'Prep Item / Recipe',
        type: 'record-search',
        entity: 'PrepLibraryItem',
        placeholder: 'Search prep library',
        searchFields: ['name', 'category'],
        displayFields: ['name', 'category'],
        map: {
          recipe_id: 'id',
          recipe_name: 'name',
          title: 'name',
        },
      },
      {
        name: 'equipment_id',
        label: 'Equipment',
        type: 'record-search',
        entity: 'Equipment',
        placeholder: 'Search equipment',
        searchFields: ['name', 'station_name', 'area_name', 'equipmentType'],
        displayFields: ['name', 'station_name'],
        map: {
          equipment_id: 'id',
          equipment_name: 'name',
          station_id: 'station_id',
          station_name: 'station_name',
          area_id: 'area_id',
          area_name: 'area_name',
        },
      },
      {
        name: 'area_id',
        label: 'Area',
        type: 'record-search',
        entity: 'Area',
        placeholder: 'Search areas',
        searchFields: ['name'],
        displayFields: ['name'],
        map: {
          area_id: 'id',
          area_name: 'name',
        },
      },
      {
        name: 'station_id',
        label: 'Station',
        type: 'record-search',
        entity: 'Station',
        required: true,
        placeholder: 'Search stations',
        searchFields: ['name', 'area_name', 'department'],
        displayFields: ['name', 'area_name'],
        map: {
          station_id: 'id',
          station_name: 'name',
          area_id: 'area_id',
          area_name: 'area_name',
        },
      },
      {
        name: 'location_id',
        label: 'Location',
        type: 'record-search',
        entity: 'Location',
        required: true,
        placeholder: 'Search locations',
        searchFields: ['name', 'type'],
        displayFields: ['name', 'type'],
        map: {
          location_id: 'id',
          location_name: 'name',
        },
      },
      {
        name: 'assigned_to_email',
        label: 'Assigned To',
        type: 'record-search',
        entity: 'Employee',
        placeholder: 'Search employees',
        searchFields: ['full_name', 'email', 'primary_role', 'job_code'],
        displayFields: ['full_name', 'primary_role'],
        map: {
          assigned_to_email: 'email',
          assigned_to_name: 'full_name',
        },
      },
      { name: 'description', label: 'Notes', type: 'textarea', placeholder: 'Add context, standards, or handoff notes' },
      { name: 'due_time', label: 'Due Time', type: 'time' },
      {
        name: 'priority',
        label: 'Priority',
        type: 'select',
        options: ['low', 'medium', 'high', 'critical'],
      },
      { name: 'requires_photo', label: 'Photo required', type: 'checkbox' },
      { name: 'requires_approval', label: 'Requires manager review', type: 'checkbox' },
    ],
  },
  manager_log: {
    id: 'manager_log',
    actionTypes: ['add_manager_note', 'manager_note', 'add_manager_log'],
    title: 'Manager Log',
    eyebrow: 'Log',
    entity: 'UnifiedLog',
    successLabel: 'Manager log',
    submitLabel: 'Save Log',
    defaults: {
      type: 'manager_note',
      status: 'open',
      priority: 'medium',
      visibility: 'manager_only',
      manager_only: true,
      follow_up_required: false,
    },
    fields: [
      { name: 'title', label: 'Subject', type: 'text', required: true, placeholder: 'Shift note, follow-up, or handoff' },
      {
        name: 'employee_id',
        label: 'Linked Employee',
        type: 'record-search',
        entity: 'Employee',
        placeholder: 'Search employees',
        searchFields: ['full_name', 'email', 'primary_role', 'job_code'],
        displayFields: ['full_name', 'primary_role'],
        privacyNote: 'Manager-only. This does not notify the employee.',
        map: {
          employee_id: 'id',
          employee_name: 'full_name',
        },
      },
      {
        name: 'location_id',
        label: 'Location',
        type: 'record-search',
        entity: 'Location',
        placeholder: 'Search locations',
        searchFields: ['name', 'type'],
        displayFields: ['name', 'type'],
        map: {
          location_id: 'id',
          location: 'name',
        },
      },
      {
        name: 'station_id',
        label: 'Station',
        type: 'record-search',
        entity: 'Station',
        placeholder: 'Search stations',
        searchFields: ['name', 'area_name', 'department'],
        displayFields: ['name', 'area_name'],
        map: {
          station_id: 'id',
          station_name: 'name',
        },
      },
      { name: 'description', label: 'Details', type: 'textarea', placeholder: 'What should the next manager know?' },
      {
        name: 'priority',
        label: 'Priority',
        type: 'select',
        options: ['low', 'medium', 'high', 'critical'],
      },
      { name: 'follow_up_required', label: 'Follow-up required', type: 'checkbox' },
    ],
  },
  beo_event: {
    id: 'beo_event',
    actionTypes: ['add_beo'],
    title: 'Reservation / BEO',
    eyebrow: 'Event',
    entity: 'BEO',
    successLabel: 'Event',
    submitLabel: 'Create Event',
    defaults: {
      eventType: 'private-dining',
      serviceStyle: 'plated',
      status: 'tentative',
      eventDate: new Date().toISOString().split('T')[0],
    },
    fields: [
      { name: 'eventName', label: 'Event Name', type: 'text', required: true, placeholder: 'Private dinner, buyout, tasting' },
      { name: 'clientName', label: 'Client', type: 'text', placeholder: 'Guest or company name' },
      { name: 'eventDate', label: 'Date', type: 'date' },
      { name: 'startTime', label: 'Start', type: 'time' },
      { name: 'endTime', label: 'End', type: 'time' },
      { name: 'guestCount', label: 'Guests', type: 'number', placeholder: '24' },
      { name: 'room', label: 'Room', type: 'text', placeholder: 'Patio, private room' },
      {
        name: 'eventType',
        label: 'Type',
        type: 'select',
        options: ['private-dining', 'banquet', 'buyout', 'catering', 'meeting', 'corporate', 'other'],
      },
      {
        name: 'linkedMenuItems',
        label: 'Banquet Menu',
        type: 'record-multi-search',
        entity: 'BuildCard',
        placeholder: 'Search menu / build cards',
        searchFields: ['name', 'category', 'station'],
        displayFields: ['name', 'category'],
      },
      {
        name: 'linkedPrepItems',
        label: 'Prep Items',
        type: 'record-multi-search',
        entity: 'PrepLibraryItem',
        placeholder: 'Search linked prep',
        searchFields: ['name', 'category'],
        displayFields: ['name', 'category'],
      },
      { name: 'prepNotes', label: 'Prep Notes', type: 'textarea', placeholder: 'Kitchen, bar, setup, or timing notes' },
      { name: 'setupNotes', label: 'Setup Notes', type: 'textarea', placeholder: 'Room setup, stations, rentals, service notes' },
    ],
  },
  waste_log: {
    id: 'waste_log',
    actionTypes: ['add_waste', 'waste'],
    title: 'Waste',
    eyebrow: 'Log',
    entity: 'UnifiedLog',
    successLabel: 'Waste log',
    submitLabel: 'Save Waste',
    defaults: {
      type: 'waste',
      status: 'open',
      priority: 'medium',
      visibility: 'team_log',
      follow_up_required: false,
    },
    fields: [
      { name: 'title', label: 'Item', type: 'text', required: true, placeholder: 'What was wasted or 86’d?' },
      { name: 'description', label: 'Reason', type: 'textarea', placeholder: 'Spoiled, over-prepped, misfire, broken package' },
      {
        name: 'station_id',
        label: 'Station',
        type: 'record-search',
        entity: 'Station',
        placeholder: 'Search stations',
        searchFields: ['name', 'area_name', 'department'],
        displayFields: ['name', 'area_name'],
        map: {
          station_id: 'id',
          station_name: 'name',
          location: 'name',
        },
      },
      {
        name: 'employee_id',
        label: 'Recorded By',
        type: 'record-search',
        entity: 'Employee',
        placeholder: 'Search employees',
        searchFields: ['full_name', 'email', 'primary_role', 'job_code'],
        displayFields: ['full_name', 'primary_role'],
        map: {
          employee_id: 'id',
          employee_name: 'full_name',
        },
      },
      { name: 'follow_up_required', label: 'Needs follow-up', type: 'checkbox' },
    ],
  },
  maintenance_issue: {
    id: 'maintenance_issue',
    actionTypes: ['report_maintenance', 'maintenance', 'add_maintenance'],
    title: 'Maintenance Issue',
    eyebrow: 'Issue',
    entity: 'UnifiedLog',
    successLabel: 'Maintenance issue',
    submitLabel: 'Report Issue',
    defaults: {
      type: 'maintenance',
      status: 'open',
      priority: 'high',
      visibility: 'team_log',
      follow_up_required: true,
    },
    fields: [
      { name: 'title', label: 'Issue', type: 'text', required: true, placeholder: 'What is broken or needs attention?' },
      { name: 'description', label: 'Details', type: 'textarea', placeholder: 'What happened? Is it still usable?' },
      {
        name: 'equipment_id',
        label: 'Equipment',
        type: 'record-search',
        entity: 'Equipment',
        placeholder: 'Search equipment',
        searchFields: ['name', 'station_name', 'area_name', 'equipmentType'],
        displayFields: ['name', 'station_name'],
        map: {
          equipment_id: 'id',
          equipment_name: 'name',
          station_id: 'station_id',
          station_name: 'station_name',
          location: 'name',
        },
      },
      {
        name: 'priority',
        label: 'Priority',
        type: 'select',
        options: ['low', 'medium', 'high', 'critical'],
      },
      { name: 'follow_up_required', label: 'Follow-up required', type: 'checkbox' },
    ],
  },
  temperature_log: {
    id: 'temperature_log',
    actionTypes: ['log_temperature', 'temperature', 'add_temperature'],
    title: 'Temp Log',
    eyebrow: 'Food Safety',
    entity: 'UnifiedLog',
    successLabel: 'Temperature log',
    submitLabel: 'Save Temp',
    defaults: {
      type: 'temperature',
      status: 'open',
      priority: 'medium',
      visibility: 'team_log',
      follow_up_required: false,
    },
    fields: [
      { name: 'title', label: 'Item / Equipment', type: 'text', required: true, placeholder: 'Walk-in, soup, chicken, lowboy' },
      { name: 'description', label: 'Temperature / Notes', type: 'textarea', placeholder: 'Record temp and any corrective action' },
      {
        name: 'equipment_id',
        label: 'Item / Equipment',
        type: 'record-search',
        entity: 'Equipment',
        placeholder: 'Search monitored equipment',
        searchFields: ['name', 'station_name', 'area_name', 'equipmentType'],
        displayFields: ['name', 'station_name'],
        map: {
          equipment_id: 'id',
          equipment_name: 'name',
          location: 'name',
          title: 'name',
        },
      },
      {
        name: 'employee_id',
        label: 'Checked By',
        type: 'record-search',
        entity: 'Employee',
        placeholder: 'Search employees',
        searchFields: ['full_name', 'email', 'primary_role', 'job_code'],
        displayFields: ['full_name', 'primary_role'],
        map: {
          employee_id: 'id',
          employee_name: 'full_name',
        },
      },
      { name: 'follow_up_required', label: 'Needs corrective action', type: 'checkbox' },
    ],
  },
  incident_report: {
    id: 'incident_report',
    actionTypes: ['report_incident', 'incident', 'add_incident'],
    title: 'Incident',
    eyebrow: 'Report',
    entity: 'UnifiedLog',
    successLabel: 'Incident',
    submitLabel: 'Report Incident',
    defaults: {
      type: 'incident',
      status: 'open',
      priority: 'critical',
      visibility: 'manager_only',
      manager_only: true,
      follow_up_required: true,
    },
    fields: [
      { name: 'title', label: 'Incident', type: 'text', required: true, placeholder: 'Short summary' },
      { name: 'description', label: 'Details', type: 'textarea', placeholder: 'What happened, who was involved, and what action was taken?' },
      {
        name: 'location_id',
        label: 'Location',
        type: 'record-search',
        entity: 'Location',
        placeholder: 'Search locations',
        searchFields: ['name', 'type'],
        displayFields: ['name', 'type'],
        map: {
          location_id: 'id',
          location: 'name',
        },
      },
      {
        name: 'employee_id',
        label: 'Person Involved',
        type: 'record-search',
        entity: 'Employee',
        placeholder: 'Search employees',
        searchFields: ['full_name', 'email', 'primary_role', 'job_code'],
        displayFields: ['full_name', 'primary_role'],
        map: {
          employee_id: 'id',
          employee_name: 'full_name',
        },
      },
      {
        name: 'priority',
        label: 'Severity',
        type: 'select',
        options: ['medium', 'high', 'critical'],
      },
      { name: 'follow_up_required', label: 'Follow-up required', type: 'checkbox' },
    ],
  },
  employee_note: {
    id: 'employee_note',
    actionTypes: ['add_employee_note', 'employee_note'],
    title: 'Employee Note',
    eyebrow: 'People',
    entity: 'UnifiedLog',
    successLabel: 'Employee note',
    submitLabel: 'Save Note',
    defaults: {
      type: 'employee_note',
      status: 'open',
      priority: 'medium',
      visibility: 'manager_only',
      manager_only: true,
      follow_up_required: false,
    },
    fields: [
      { name: 'title', label: 'Note', type: 'text', required: true, placeholder: 'Coaching, praise, follow-up' },
      {
        name: 'employee_id',
        label: 'Linked Employee',
        type: 'record-search',
        entity: 'Employee',
        placeholder: 'Search employees',
        searchFields: ['full_name', 'email', 'primary_role', 'job_code'],
        displayFields: ['full_name', 'primary_role'],
        privacyNote: 'Manager-only. This does not notify the employee.',
        map: {
          employee_id: 'id',
          employee_name: 'full_name',
        },
      },
      { name: 'description', label: 'Details', type: 'textarea', placeholder: 'What happened? What is the follow-up?' },
      {
        name: 'location_id',
        label: 'Location',
        type: 'record-search',
        entity: 'Location',
        placeholder: 'Search locations',
        searchFields: ['name', 'type'],
        displayFields: ['name', 'type'],
        map: {
          location_id: 'id',
          location: 'name',
        },
      },
      { name: 'follow_up_required', label: 'Follow-up required', type: 'checkbox' },
    ],
  },
  bathroom_check: {
    id: 'bathroom_check',
    actionTypes: ['bathroom', 'add_bathroom_check'],
    title: 'Bathroom Check',
    eyebrow: 'Facilities',
    entity: 'UnifiedLog',
    successLabel: 'Bathroom check',
    submitLabel: 'Save Check',
    defaults: {
      type: 'bathroom',
      status: 'open',
      priority: 'medium',
      visibility: 'team_log',
      follow_up_required: false,
    },
    fields: [
      { name: 'title', label: 'Area', type: 'text', required: true, placeholder: 'Guest restroom, patio restroom' },
      { name: 'description', label: 'Notes', type: 'textarea', placeholder: 'Stocked, clean, issue found, corrective action' },
      {
        name: 'location_id',
        label: 'Location',
        type: 'record-search',
        entity: 'Location',
        placeholder: 'Search locations',
        searchFields: ['name', 'type'],
        displayFields: ['name', 'type'],
        map: {
          location_id: 'id',
          location: 'name',
        },
      },
      {
        name: 'employee_id',
        label: 'Checked By',
        type: 'record-search',
        entity: 'Employee',
        placeholder: 'Search employees',
        searchFields: ['full_name', 'email', 'primary_role', 'job_code'],
        displayFields: ['full_name', 'primary_role'],
        map: {
          employee_id: 'id',
          employee_name: 'full_name',
        },
      },
      { name: 'follow_up_required', label: 'Needs follow-up', type: 'checkbox' },
    ],
  },
  custom_log: {
    id: 'custom_log',
    actionTypes: ['custom', 'add_custom_log'],
    title: 'Custom Log',
    eyebrow: 'Log',
    entity: 'UnifiedLog',
    successLabel: 'Log',
    submitLabel: 'Save Log',
    defaults: {
      type: 'custom',
      status: 'open',
      priority: 'medium',
      visibility: 'team_log',
      follow_up_required: false,
    },
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, placeholder: 'What should be logged?' },
      { name: 'description', label: 'Details', type: 'textarea', placeholder: 'Add context, action taken, or follow-up' },
      {
        name: 'location_id',
        label: 'Location',
        type: 'record-search',
        entity: 'Location',
        placeholder: 'Search locations',
        searchFields: ['name', 'type'],
        displayFields: ['name', 'type'],
        map: {
          location_id: 'id',
          location: 'name',
        },
      },
      {
        name: 'employee_id',
        label: 'Employee',
        type: 'record-search',
        entity: 'Employee',
        placeholder: 'Search employees',
        searchFields: ['full_name', 'email', 'primary_role', 'job_code'],
        displayFields: ['full_name', 'primary_role'],
        map: {
          employee_id: 'id',
          employee_name: 'full_name',
        },
      },
      { name: 'follow_up_required', label: 'Follow-up required', type: 'checkbox' },
    ],
  },
  prep_task: {
    id: 'prep_task',
    actionTypes: ['add_prep_item'],
    title: 'Prep Task',
    eyebrow: 'Prep',
    entity: 'Task',
    successLabel: 'Prep task',
    submitLabel: 'Create Prep',
    defaults: {
      shift_id: 'quick-add',
      status: 'pending',
      priority: 'medium',
      created_from_template: true,
      requires_photo: false,
      requires_approval: false,
    },
    fields: [
      { name: 'title', label: 'Prep Item', type: 'text', required: true, placeholder: 'Ranch, pico, cut romaine' },
      {
        name: 'recipe_id',
        label: 'Linked Prep Item',
        type: 'record-search',
        entity: 'PrepLibraryItem',
        placeholder: 'Search prep library',
        searchFields: ['name', 'category'],
        displayFields: ['name', 'category'],
        map: {
          recipe_id: 'id',
          recipe_name: 'name',
          title: 'name',
        },
      },
      { name: 'description', label: 'Notes', type: 'textarea', placeholder: 'Batch size, recipe notes, storage notes' },
      {
        name: 'station_id',
        label: 'Station',
        type: 'record-search',
        entity: 'Station',
        required: true,
        placeholder: 'Search stations',
        searchFields: ['name', 'area_name', 'department'],
        displayFields: ['name', 'area_name'],
        map: {
          station_id: 'id',
          station_name: 'name',
          area_id: 'area_id',
          area_name: 'area_name',
        },
      },
      {
        name: 'location_id',
        label: 'Location',
        type: 'record-search',
        entity: 'Location',
        required: true,
        placeholder: 'Search locations',
        searchFields: ['name', 'type'],
        displayFields: ['name', 'type'],
        map: {
          location_id: 'id',
          location_name: 'name',
        },
      },
      {
        name: 'assigned_to_email',
        label: 'Assigned To',
        type: 'record-search',
        entity: 'Employee',
        placeholder: 'Search employees',
        searchFields: ['full_name', 'email', 'primary_role', 'job_code'],
        displayFields: ['full_name', 'primary_role'],
        map: {
          assigned_to_email: 'email',
          assigned_to_name: 'full_name',
        },
      },
      { name: 'due_time', label: 'Due Time', type: 'time' },
      { name: 'requires_photo', label: 'Photo required', type: 'checkbox' },
    ],
  },
  sidework_task: {
    id: 'sidework_task',
    actionTypes: ['add_side_work'],
    title: 'Sidework Task',
    eyebrow: 'Sidework',
    entity: 'Task',
    successLabel: 'Sidework task',
    submitLabel: 'Create Sidework',
    defaults: {
      shift_id: 'quick-add',
      status: 'pending',
      priority: 'medium',
      created_from_template: true,
      requires_photo: false,
      requires_approval: false,
    },
    fields: [
      { name: 'title', label: 'Sidework', type: 'text', required: true, placeholder: 'Restock, wipe, polish, reset' },
      { name: 'description', label: 'Notes', type: 'textarea', placeholder: 'Standard or completion notes' },
      {
        name: 'station_id',
        label: 'Station',
        type: 'record-search',
        entity: 'Station',
        required: true,
        placeholder: 'Search stations',
        searchFields: ['name', 'area_name', 'department'],
        displayFields: ['name', 'area_name'],
        map: {
          station_id: 'id',
          station_name: 'name',
          area_id: 'area_id',
          area_name: 'area_name',
        },
      },
      {
        name: 'location_id',
        label: 'Location',
        type: 'record-search',
        entity: 'Location',
        required: true,
        placeholder: 'Search locations',
        searchFields: ['name', 'type'],
        displayFields: ['name', 'type'],
        map: {
          location_id: 'id',
          location_name: 'name',
        },
      },
      {
        name: 'assigned_to_email',
        label: 'Assigned To',
        type: 'record-search',
        entity: 'Employee',
        placeholder: 'Search employees',
        searchFields: ['full_name', 'email', 'primary_role', 'job_code'],
        displayFields: ['full_name', 'primary_role'],
        map: {
          assigned_to_email: 'email',
          assigned_to_name: 'full_name',
        },
      },
      { name: 'due_time', label: 'Due Time', type: 'time' },
      { name: 'requires_approval', label: 'Requires manager review', type: 'checkbox' },
    ],
  },
};

export const TEMPLATE_BY_ACTION = Object.values(CREATE_TEMPLATES).reduce((map, template) => {
  template.actionTypes.forEach((actionType) => {
    map[actionType] = template.id;
  });
  return map;
}, {});

export function getCreateTemplate(templateIdOrActionType) {
  const templateId = CREATE_TEMPLATES[templateIdOrActionType]
    ? templateIdOrActionType
    : TEMPLATE_BY_ACTION[templateIdOrActionType];

  return CREATE_TEMPLATES[templateId] || null;
}
