export const quickActionsConfig = [
  {
    id: "quick-log",
    label: "Quick Log Entry",
    icon: "FileText",
    color: "bg-blue-500/15 text-blue-400",
    actionType: "modal",
    targetModal: "quickLog",
    createsRecordType: "log",
    targetPage: "/logs",
  },
  {
    id: "add-task",
    label: "Add Task",
    icon: "CheckCircle2",
    color: "bg-green-500/15 text-green-400",
    actionType: "modal",
    targetModal: "addTask",
    createsRecordType: "task",
    targetPage: "/tasks",
  },
  {
    id: "add-86",
    label: "86 / Waste",
    icon: "AlertTriangle",
    color: "bg-amber-500/15 text-amber-400",
    actionType: "modal",
    targetModal: "add86",
    createsRecordType: "eightysixtitem",
    targetPage: "/waste-86",
  },
  {
    id: "add-prep",
    label: "Add Prep Item",
    icon: "Flame",
    color: "bg-red-500/15 text-red-400",
    actionType: "modal",
    targetModal: "addPrep",
    createsRecordType: "prepitem",
    targetPage: "/prep",
  },
  {
    id: "add-maintenance",
    label: "Maintenance Issue",
    icon: "Wrench",
    color: "bg-purple-500/15 text-purple-400",
    actionType: "modal",
    targetModal: "addMaintenance",
    createsRecordType: "maintenancerequest",
    targetPage: "/maintenance",
  },
];