import { AlertTriangle, Thermometer, Utensils, Flame, Wind,
  ClipboardList, ListFilter, Wrench, ShieldAlert, User, Coffee,
  ClipboardCheck, MessageSquareWarning, ArrowRightLeft, Droplets,
} from "lucide-react";

export const LOG_TYPE_CONFIG = {
  temperature: {
    label: "Temp Log",
    icon: Thermometer,
    border: "border-l-cyan-500",
    bg: "bg-cyan-500/15",
    text: "text-cyan-400",
    badge: "bg-cyan-500/20 text-cyan-300 border-cyan-500/30",
    dot: "bg-cyan-500",
    routePath: "/logs?type=temperature",
  },
  bathroom: {
    label: "Bathroom Check",
    icon: Droplets,
    border: "border-l-purple-500",
    bg: "bg-purple-500/15",
    text: "text-purple-400",
    badge: "bg-purple-500/20 text-purple-300 border-purple-500/30",
    dot: "bg-purple-500",
    routePath: "/logs?type=bathroom",
  },
  maintenance: {
    label: "Maintenance",
    icon: Wrench,
    border: "border-l-amber-400",
    bg: "bg-amber-400/15",
    text: "text-amber-400",
    badge: "bg-amber-400/20 text-amber-300 border-amber-400/30",
    dot: "bg-amber-400",
    routePath: "/logs?type=maintenance",
  },
  incident: {
    label: "Incident",
    icon: ShieldAlert,
    border: "border-l-red-500",
    bg: "bg-red-500/15",
    text: "text-red-400",
    badge: "bg-red-500/20 text-red-300 border-red-500/30",
    dot: "bg-red-500",
    routePath: "/logs?type=incident",
  },
  employee: {
    label: "Employee Log",
    icon: User,
    border: "border-l-pink-500",
    bg: "bg-pink-500/15",
    text: "text-pink-400",
    badge: "bg-pink-500/20 text-pink-300 border-pink-500/30",
    dot: "bg-pink-500",
    routePath: "/team",
  },
  manager: {
    label: "Manager Note",
    icon: Coffee,
    border: "border-l-orange-500",
    bg: "bg-orange-500/15",
    text: "text-orange-400",
    badge: "bg-orange-500/20 text-orange-300 border-orange-500/30",
    dot: "bg-orange-500",
    routePath: "/logs",
  },
  food_safety: {
    label: "Food Safety",
    icon: ClipboardCheck,
    border: "border-l-teal-500",
    bg: "bg-teal-500/15",
    text: "text-teal-400",
    badge: "bg-teal-500/20 text-teal-300 border-teal-500/30",
    dot: "bg-teal-500",
    routePath: "/logs?type=temperature",
  },
  cleaning: {
    label: "Cleaning",
    icon: Wind,
    border: "border-l-green-500",
    bg: "bg-green-500/15",
    text: "text-green-400",
    badge: "bg-green-500/20 text-green-300 border-green-500/30",
    dot: "bg-green-500",
    routePath: "/cleaning",
  },
  waste: {
    label: "Waste",
    icon: Flame,
    border: "border-l-yellow-600",
    bg: "bg-yellow-600/15",
    text: "text-yellow-500",
    badge: "bg-yellow-600/20 text-yellow-400 border-yellow-600/30",
    dot: "bg-yellow-600",
    routePath: "/logs?type=waste",
  },
  eighty_six: {
    label: "86'd",
    icon: Utensils,
    border: "border-l-orange-600",
    bg: "bg-orange-600/15",
    text: "text-orange-500",
    badge: "bg-orange-600/20 text-orange-400 border-orange-600/30",
    dot: "bg-orange-600",
    routePath: "/logs?type=waste",
  },
  equipment: {
    label: "Equipment",
    icon: Wrench,
    border: "border-l-sky-500",
    bg: "bg-sky-500/15",
    text: "text-sky-400",
    badge: "bg-sky-500/20 text-sky-300 border-sky-500/30",
    dot: "bg-sky-500",
    routePath: "/logs?type=incident",
  },
  guest_complaint: {
    label: "Guest Complaint",
    icon: MessageSquareWarning,
    border: "border-l-rose-500",
    bg: "bg-rose-500/15",
    text: "text-rose-400",
    badge: "bg-rose-500/20 text-rose-300 border-rose-500/30",
    dot: "bg-rose-500",
    routePath: "/logs?type=incident",
  },
  shift_handoff: {
    label: "Shift Handoff",
    icon: ArrowRightLeft,
    border: "border-l-indigo-500",
    bg: "bg-indigo-500/15",
    text: "text-indigo-400",
    badge: "bg-indigo-500/20 text-indigo-300 border-indigo-500/30",
    dot: "bg-indigo-500",
    routePath: "/shift",
  },
  issue: {
    label: "Issue",
    icon: AlertTriangle,
    border: "border-l-red-500",
    bg: "bg-red-500/15",
    text: "text-red-400",
    badge: "bg-red-500/20 text-red-300 border-red-500/30",
    dot: "bg-red-500",
    routePath: "/logs?type=incident",
  },
  prep: {
    label: "Prep",
    icon: ClipboardList,
    border: "border-l-violet-500",
    bg: "bg-violet-500/15",
    text: "text-violet-400",
    badge: "bg-violet-500/20 text-violet-300 border-violet-500/30",
    dot: "bg-violet-500",
    routePath: "/tasks?tab=prep",
  },
  side_work: {
    label: "Side Work",
    icon: ListFilter,
    border: "border-l-pink-400",
    bg: "bg-pink-400/15",
    text: "text-pink-400",
    badge: "bg-pink-400/20 text-pink-300 border-pink-400/30",
    dot: "bg-pink-400",
    routePath: "/tasks?tab=sidework",
  },
};

export const STATUS_META = {
  completed:    { label: "Done",        cls: "bg-green-500/15 text-green-400 border-green-500/30" },
  approved:     { label: "Approved",    cls: "bg-green-500/15 text-green-400 border-green-500/30" },
  flagged:      { label: "Flagged",     cls: "bg-red-500/15 text-red-400 border-red-500/30" },
  overdue:      { label: "Overdue",     cls: "bg-red-500/15 text-red-400 border-red-500/30" },
  needs_review: { label: "Review",      cls: "bg-purple-500/15 text-purple-400 border-purple-500/30" },
  open:         { label: "Open",        cls: "bg-amber-500/15 text-amber-400 border-amber-500/30" },
  in_progress:  { label: "In Progress", cls: "bg-blue-500/15 text-blue-400 border-blue-500/30" },
  not_started:  { label: "Pending",     cls: "bg-muted/80 text-muted-foreground border-border" },
  active:       { label: "Active",      cls: "bg-orange-500/15 text-orange-400 border-orange-500/30" },
  resolved:     { label: "Resolved",    cls: "bg-green-500/15 text-green-400 border-green-500/30" },
};

export const PRIORITY_COLORS = {
  critical: "text-red-400",
  high:     "text-orange-400",
  medium:   "text-amber-400",
  low:      "text-muted-foreground",
  normal:   "text-muted-foreground",
};

export const TYPE_FILTER_LIST = [
  { id: "all",             label: "All" },
  { id: "manager",         label: "Manager" },
  { id: "issue",           label: "Issues" },
  { id: "incident",        label: "Incidents" },
  { id: "maintenance",     label: "Maintenance" },
  { id: "waste",           label: "Waste" },
  { id: "eighty_six",      label: "86'd" },
  { id: "temperature",     label: "Temps" },
  { id: "food_safety",     label: "Food Safety" },
  { id: "cleaning",        label: "Cleaning" },
  { id: "prep",            label: "Prep" },
  { id: "side_work",       label: "Side Work" },
  { id: "employee",        label: "Employee" },
  { id: "shift_handoff",   label: "Shift Handoff" },
  { id: "guest_complaint", label: "Complaints" },
];
